---
- name: Configurar kubelet con flags
  hosts: all
  become: true

  tasks:
    - name: Asegurarse de que el directorio de configuración del kubelet existe
      file:
        path: /etc/kubernetes/
        state: directory

    - name: Crear o actualizar archivo de configuración del kubelet
      blockinfile:
        path: /etc/kubernetes/kubelet.conf
        block: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          authentication:
            token-webhook: true
          authorization:
            mode: Webhook
      become: true

    - name: Reiniciar kubelet
      service:
        name: kubelet
        state: restarted
