apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: local-persistence-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /var/local-storage
